version: "3.9"

services:
  # Node.js Todo App
  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app                # Mount app code for live updates
      - /app/node_modules     # Preserve container-installed node_modules
    environment:
      - NODE_ENV=production
    restart: always

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
